# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/comm-core',
                'doc_host': 'https://Ahmed-Khaled-Saleh.github.io',
                'git_url': 'https://github.com/Ahmed-Khaled-Saleh/comm-core',
                'lib_path': 'comm_core'},
  'syms': {'comm_core.core': {'comm_core.core.foo': ('core.html#foo', 'comm_core/core.py')}}}
