"""How a step's transmissions are simulated.

Docs: https://Ahmed-Khaled-Saleh.github.io/comm-core/backend.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/backend.ipynb.

# %% ../nbs/backend.ipynb #719f316b
from __future__ import annotations

from abc import ABC, abstractmethod
from typing import List, Tuple

from .core import Transmission, TransmissionResult
from .topology import Link
from .channel import Channel


class CommunicationBackend(ABC):

    @abstractmethod
    def transmit(
        self,
        transmission: Transmission,
        link: Link,
    ) -> TransmissionResult:
        pass

    def transmit_all(
        self,
        transmissions: List[Tuple[Transmission, Link]], # The transmissions of one step, with their links
    ) -> List[TransmissionResult]:
        "The transmissions of one step, all at once (they may affect each other, e.g. interfere); by default one at a time."
        return [self.transmit(transmission, link) for transmission, link in transmissions]

    def reset(self, seed: int | None = None) -> None:
        "Start over; `seed` reseeds the randomness of the simulation."
        pass

    def step(self, time: float) -> None:
        pass


class AnalyticalBackend(CommunicationBackend):

    def __init__(
        self,
        channel: Channel,
    ):
        self.channel = channel

    def transmit(
        self,
        transmission: Transmission,
        link: Link,
    ) -> TransmissionResult:

        return self.channel.transmit(
            transmission,
            link,
        )

    def reset(self, seed: int | None = None) -> None:
        self.channel.reset(seed)

    def step(self, time: float) -> None:
        self.channel.update(time)
        

# %% auto #0
__all__ = ['CommunicationBackend', 'AnalyticalBackend']
