# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/backend.ipynb.

# %% ../nbs/backend.ipynb #719f316b
from __future__ import annotations

from abc import ABC, abstractmethod

from .core import Transmission, TransmissionResult
from .topology import Link
from .channel import Channel


class CommunicationBackend(ABC):

    @abstractmethod
    def transmit(
        self,
        transmission: Transmission,
        link: Link,
    ) -> TransmissionResult:
        pass

    def reset(self) -> None:
        pass

    def step(self, time: float) -> None:
        pass


class AnalyticalBackend(CommunicationBackend):

    def __init__(
        self,
        channel: Channel,
    ):
        self.channel = channel

    def transmit(
        self,
        transmission: Transmission,
        link: Link,
    ) -> TransmissionResult:

        return self.channel.transmit(
            transmission,
            link,
        )

    def reset(self) -> None:
        self.channel.reset()

    def step(self, time: float) -> None:
        self.channel.update(time)
        

# %% auto #0
__all__ = ['CommunicationBackend', 'AnalyticalBackend']
