# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/channel.ipynb.

# %% ../nbs/channel.ipynb #fb9c67cb
# channel.py

from __future__ import annotations

import random
from abc import ABC, abstractmethod

from .core import Transmission, TransmissionResult
from .topology import Link


    

# %% auto #0
__all__ = ['Channel', 'IdentityChannel', 'AWGNChannel']

# %% ../nbs/channel.ipynb #3172a976
class Channel(ABC):

    @abstractmethod
    def transmit(
        self,
        transmission: Transmission,
        link: Link,
    ) -> TransmissionResult:
        pass

    def reset(self, seed: int | None = None) -> None:
        "Start over (e.g. a new episode); `seed` reseeds the channel's random generator, if it has one."
        pass

    def update(self, time: float) -> None:
        pass

# %% ../nbs/channel.ipynb #b13245fb
class IdentityChannel(Channel):
    """
    Perfect communication.
    """

    def transmit(
        self,
        transmission: Transmission,
        link: Link,
    ) -> TransmissionResult:

        message = transmission.message

        return TransmissionResult(
            success=True,
            transmission=transmission,
            payload=message.payload,
            latency=0.0,
            size_bits=message.size_bits or 0,
            snr_db=float("inf"),
            error_rate=0.0,
        )




# %% ../nbs/channel.ipynb #1b262752
class AWGNChannel(Channel):
    """
    Simple analytical channel.

    This intentionally models only packet success/failure
    rather than individual bits.
    """

    def __init__(
        self,
        snr_db: float, # Signal-to-noise ratio (reported in the results)
        packet_error_rate: float = 0.0, # Probability that a packet is lost
        seed: int | None = None, # Seed of the channel's own random generator
    ):
        self.snr_db = snr_db
        self.packet_error_rate = packet_error_rate
        self.rng = random.Random(seed)

    def reset(self, seed: int | None = None) -> None:
        "`seed` reseeds the packet losses."
        if seed is not None:
            self.rng.seed(seed)

    def transmit(
        self,
        transmission: Transmission,
        link: Link,
    ) -> TransmissionResult:

        success = (
            self.rng.random()
            >= self.packet_error_rate
        )

        message = transmission.message

        return TransmissionResult(
            success=success,
            transmission=transmission,
            payload=(
                message.payload
                if success
                else None
            ),
            latency=0.0,
            size_bits=message.size_bits or 0,
            snr_db=self.snr_db,
            error_rate=self.packet_error_rate,
        )
