"""What happens to one transmission.

Docs: https://Ahmed-Khaled-Saleh.github.io/comm-core/channel.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/channel.ipynb.

# %% ../nbs/channel.ipynb #fb9c67cb
# channel.py

from __future__ import annotations

import random
from dataclasses import replace
from abc import ABC, abstractmethod

from .core import Transmission, TransmissionResult
from .topology import Link


    

# %% auto #0
__all__ = ['Channel', 'IdentityChannel', 'AWGNChannel', 'FragmentingChannel']

# %% ../nbs/channel.ipynb #3172a976
class Channel(ABC):

    @abstractmethod
    def transmit(
        self,
        transmission: Transmission,
        link: Link,
    ) -> TransmissionResult:
        pass

    def reset(self, seed: int | None = None) -> None:
        "Start over (e.g. a new episode); `seed` reseeds the channel's random generator, if it has one."
        pass

    def update(self, time: float) -> None:
        pass

# %% ../nbs/channel.ipynb #b13245fb
class IdentityChannel(Channel):
    """
    Perfect communication.
    """

    def transmit(
        self,
        transmission: Transmission,
        link: Link,
    ) -> TransmissionResult:

        message = transmission.message

        return TransmissionResult(
            success=True,
            transmission=transmission,
            payload=message.payload,
            latency=0.0,
            size_bits=message.size_bits or 0,
            snr_db=float("inf"),
            error_rate=0.0,
        )




# %% ../nbs/channel.ipynb #1b262752
class AWGNChannel(Channel):
    """
    Simple analytical channel.

    This intentionally models only packet success/failure
    rather than individual bits.
    """

    def __init__(
        self,
        snr_db: float, # Signal-to-noise ratio (reported in the results)
        packet_error_rate: float = 0.0, # Probability that a packet is lost
        seed: int | None = None, # Seed of the channel's own random generator
    ):
        self.snr_db = snr_db
        self.packet_error_rate = packet_error_rate
        self.rng = random.Random(seed)

    def reset(self, seed: int | None = None) -> None:
        "`seed` reseeds the packet losses."
        if seed is not None:
            self.rng.seed(seed)

    def transmit(
        self,
        transmission: Transmission,
        link: Link,
    ) -> TransmissionResult:

        success = (
            self.rng.random()
            >= self.packet_error_rate
        )

        message = transmission.message

        return TransmissionResult(
            success=success,
            transmission=transmission,
            payload=(
                message.payload
                if success
                else None
            ),
            latency=0.0,
            size_bits=message.size_bits or 0,
            snr_db=self.snr_db,
            error_rate=self.packet_error_rate,
        )

# %% ../nbs/channel.ipynb #035d1016
class FragmentingChannel(Channel):
    "A MAC layer over another channel: packets of at most `mtu_bits`, each retried; the message arrives if every packet does."

    def __init__(
        self,
        channel: Channel, # The channel of each packet (deciding from its size, e.g. `SystemLevelChannel`)
        mtu_bits: int = 12_000, # Largest packet (1500 bytes)
        retry_limit: int = 7, # Retransmissions of a packet before the message is lost
        overhead_s: float = 0.0, # Time added to every attempt (preamble, backoff, acknowledgement)
        rate_bps: float | None = None, # Bit rate of the airtime; None: the inner channel's latency
    ):
        self.channel, self.mtu_bits, self.retry_limit = channel, mtu_bits, retry_limit
        self.overhead_s, self.rate_bps = overhead_s, rate_bps

    def reset(self, seed: int | None = None) -> None:
        self.channel.reset(seed)

    def update(self, time: float) -> None:
        self.channel.update(time)

    def set_positions(self, positions) -> None:
        "Where the nodes are, for an inner channel that depends on it."
        if hasattr(self.channel, 'set_positions'):
            self.channel.set_positions(positions)

    def transmit(
        self,
        transmission: Transmission,
        link: Link,
    ) -> TransmissionResult:

        message = transmission.message
        size = message.size_bits or 0
        packets = [self.mtu_bits] * (size // self.mtu_bits) + ([size % self.mtu_bits] if size % self.mtu_bits or not size else [])
        time, attempts, bits_on_air, energy, ok, last = transmission.start_time, 0, 0, 0.0, True, None
        for bits in packets:
            for _ in range(self.retry_limit + 1):
                packet = replace(transmission, message=replace(message, size_bits=bits), start_time=time, end_time=None)
                last = self.channel.transmit(packet, link)
                attempts, bits_on_air, energy = attempts + 1, bits_on_air + bits, energy + last.energy
                time += (bits / self.rate_bps if self.rate_bps else last.latency) + self.overhead_s
                if last.success:
                    break
            else:
                ok = False
                break
        return TransmissionResult(
            success=ok,
            transmission=transmission,
            payload=message.payload if ok else None,
            latency=time - transmission.start_time,
            size_bits=size,
            energy=energy,
            snr_db=last.snr_db,
            error_rate=last.error_rate,
            metadata={**last.metadata, 'packets': len(packets), 'attempts': attempts, 'bits_on_air': bits_on_air},
        )
