"""The data that flows through a network: nodes, messages, transmissions and their results.

Docs: https://Ahmed-Khaled-Saleh.github.io/comm-core/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% ../nbs/00_core.ipynb #21479dbb
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, Optional
from uuid import uuid4


# %% auto #0
__all__ = ['NodeId', 'MessageId', 'TransmissionId', 'Node', 'Message', 'Transmission', 'TransmissionResult']

# %% ../nbs/00_core.ipynb #7662746d
NodeId = str
MessageId = str
TransmissionId = str


# %% ../nbs/00_core.ipynb #da4d26dd
@dataclass(frozen=True)
class Node:
    """
    Passive communication participant.

    The node does NOT know how to send or receive.
    Learning/application code decides when communication happens.
    """
    id: NodeId



# %% ../nbs/00_core.ipynb #46d37bd9
@dataclass
class Message:
    """
    Semantic information exchanged between nodes.
    """
    sender: NodeId
    receiver: NodeId
    payload: Any

    type: str = "generic"
    timestamp: float = 0.0
    size_bits: Optional[int] = None

    id: MessageId = field(
        default_factory=lambda: str(uuid4())
    )

    metadata: Dict[str, Any] = field(default_factory=dict)



# %% ../nbs/00_core.ipynb #60828b7f
@dataclass
class Transmission:
    """
    One actual communication attempt.

    A Message can result in multiple Transmissions,
    e.g. because of retransmissions.
    """
    message: Message
    sender: NodeId
    receiver: NodeId

    start_time: float
    end_time: Optional[float] = None

    id: TransmissionId = field(
        default_factory=lambda: str(uuid4())
    )


# %% ../nbs/00_core.ipynb #1325a7e6
@dataclass
class TransmissionResult:
    """
    Result of a communication attempt.
    """
    success: bool

    transmission: Transmission

    payload: Any = None

    latency: float = 0.0
    size_bits: int = 0

    energy: float = 0.0
    snr_db: Optional[float] = None
    error_rate: Optional[float] = None

    metadata: Dict[str, Any] = field(default_factory=dict)
