"""Every bit of a transmission: codecs, modulation, noise, detection, and the channel built on them.

Docs: https://Ahmed-Khaled-Saleh.github.io/comm-core/link.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/link.ipynb.

# %% ../nbs/link.ipynb #c8a17ec4
from __future__ import annotations

import math
from abc import ABC, abstractmethod

import numpy as np

from .core import Message, Transmission, TransmissionResult
from .propagation import Fading
from .system import LinkBudget, PowerControl, RadioChannel, _is_torch
from .topology import Link

# %% auto #0
__all__ = ['to_bits', 'from_bits', 'Codec', 'IndexCodec', 'UniformQuantizer', 'Modulation', 'BPSK', 'awgn', 'propagate',
           'LinkLevelChannel']

# %% ../nbs/link.ipynb #6c8f6ee6
def _arange(n: int, like):
    "0, ..., n-1: a torch tensor on `like`'s device if `like` is one, else a numpy array."
    if _is_torch(like):
        import torch
        return torch.arange(n, device=like.device)
    return np.arange(n)


def _conj(h):
    return h.conj() if _is_torch(h) else np.conj(h)


def _real(z):
    if _is_torch(z):
        return z.real if z.is_complex() else z
    return np.real(z)


def _as_array(x, dtype=None):
    "Tensors stay tensors; anything else becomes a numpy array (at least 1-d)."
    return x if _is_torch(x) else np.atleast_1d(np.asarray(x, dtype=dtype))

# %% ../nbs/link.ipynb #e354e97f
def to_bits(
    indices, # Integers, (..., M)
    bits_per_index: int, # Bits per integer
):
    "The bits of `indices`: (..., M * bits_per_index), least significant bit first."
    shifts = _arange(bits_per_index, indices)
    bits = (indices[..., None] >> shifts) & 1
    return bits.reshape(*indices.shape[:-1], -1)


def from_bits(
    bits, # 0/1 or booleans, (..., M * bits_per_index)
    bits_per_index: int, # Bits per integer
):
    "The integers of `bits` (the inverse of `to_bits`): (..., M)."
    weights = 2 ** _arange(bits_per_index, bits)
    return (bits.reshape(*bits.shape[:-1], -1, bits_per_index) * weights).sum(-1)

# %% ../nbs/link.ipynb #a6ec2120
class Codec(ABC):
    "Payload <-> bits."

    @abstractmethod
    def encode(self, payload):
        "The payload's bits: (..., num_bits) of 0/1."

    @abstractmethod
    def decode(self, bits):
        "The payload of `bits`, which may have bit errors."


class IndexCodec(Codec):
    "Indices into a codebook (e.g. a VQ-VAE's), with ceil(log2(codebook_size)) bits each."

    def __init__(
        self,
        codebook_size: int = 256, # Number of codewords
    ):
        self.codebook_size = codebook_size
        self.bits_per_index = max(1, math.ceil(math.log2(codebook_size)))

    def encode(self, payload):
        "`payload`: integers in [0, codebook_size), (..., M)."
        x = _as_array(payload)
        if _is_torch(x):
            integer = not (x.is_floating_point() or x.is_complex()) and str(x.dtype) != 'torch.bool'
        else:
            integer = np.issubdtype(x.dtype, np.integer)
        if not integer:
            raise TypeError(f"IndexCodec encodes integers, not {x.dtype}")
        if (x < 0).any() or (x >= self.codebook_size).any():
            raise ValueError(f"indices must be in [0, {self.codebook_size})")
        return to_bits(x, self.bits_per_index)

    def decode(self, bits):
        "Indices (..., M). Bit errors can give indices >= codebook_size if it is not a power of 2."
        return from_bits(bits, self.bits_per_index)


class UniformQuantizer(Codec):
    "Real numbers in [low, high], each rounded to one of 2**bits evenly spaced levels (values outside are clipped)."

    def __init__(
        self,
        bits: int = 8, # Bits per number
        low: float = -1.0, # Smallest value
        high: float = 1.0, # Largest value
    ):
        self.bits, self.low, self.high = bits, low, high
        self.levels = 2 ** bits - 1

    def encode(self, payload):
        x = _as_array(payload, dtype=float)
        q = ((x.clip(self.low, self.high) - self.low) / (self.high - self.low) * self.levels).round()
        return to_bits(q.long() if _is_torch(q) else q.astype(np.int64), self.bits)

    def decode(self, bits):
        return self.low + from_bits(bits, self.bits) * ((self.high - self.low) / self.levels)

# %% ../nbs/link.ipynb #a08e5c3f
class Modulation(ABC):
    "Bits <-> symbols."

    bits_per_symbol: int = 1

    @abstractmethod
    def modulate(self, bits):
        "Symbols (..., num_bits / bits_per_symbol), with average energy 1."

    @abstractmethod
    def demodulate(self, received, h):
        "The detected bits (booleans) of the received symbols, knowing the channel coefficients `h`."


class BPSK(Modulation):
    "Binary phase-shift keying: bit 0 -> -1, bit 1 -> +1."

    bits_per_symbol = 1

    def modulate(self, bits):
        return 2.0 * bits - 1.0

    def demodulate(self, received, h):
        "Matched filter, which is the maximum-likelihood detector for BPSK: the sign of Re(y h*)."
        return _real(received * _conj(h)) > 0

# %% ../nbs/link.ipynb #06cfbbdb
def awgn(
    like, # Array or tensor whose shape (and device) the noise takes
    noise_power, # Noise power (variance of the complex noise)
    rng=None, # numpy: a Generator or seed; torch: a torch.Generator or None
):
    "Complex Gaussian noise, CN(0, noise_power)."
    std = (noise_power / 2) ** 0.5
    if _is_torch(like):
        import torch
        re = torch.randn(like.shape, generator=rng, device=like.device)
        im = torch.randn(like.shape, generator=rng, device=like.device)
        return torch.complex(re, im) * std
    rng = np.random.default_rng(rng)
    shape = np.shape(like)
    return (rng.standard_normal(shape) + 1j * rng.standard_normal(shape)) * std


def propagate(
    symbols, # Transmitted symbols x, (..., num_symbols)
    h, # Channel coefficients (complex), broadcast against the symbols, e.g. (..., 1): one per packet
    power, # Transmit power P, broadcast against the symbols
    noise_power, # Noise power at the receiver
    rng=None, # Random generator of the noise (see `awgn`)
):
    "What the receiver gets: y = h √P x + n."
    signal = h * power ** 0.5 * symbols
    return signal + awgn(signal, noise_power, rng)

# %% ../nbs/link.ipynb #7300dcd8
class LinkLevelChannel(RadioChannel):
    "Every bit simulated: payload -> bits -> symbols -> h √P x + n -> detected bits -> payload (with its bit errors)."

    def __init__(
        self,
        codec: Codec | None = None, # Payload <-> bits; None: `IndexCodec(256)`
        modulation: Modulation | None = None, # Bits <-> symbols; None: `BPSK()`
        fading: Fading | None = None, # The coefficient h of a transmission; None: h = 1
        power_control: PowerControl | None = None, # Transmit power and outages; None: the link's tx_power_w
        noise_power: float = 1.0, # Noise power at the receiver (same unit as the power)
        drop_corrupted: bool = False, # Lose the packets with bit errors (a CRC) instead of delivering them
        seed: int | None = None, # Seed of the noise and the fading
    ):
        self.codec = codec if codec is not None else IndexCodec()
        self.modulation = modulation if modulation is not None else BPSK()
        self.drop_corrupted = drop_corrupted
        super().__init__(fading, power_control, noise_power, seed)

    def transmit(
        self,
        transmission: Transmission,
        link: Link,
        interference: float = 0.0, # Power of the other transmissions at the receiver (see `InterferenceBackend`)
        budget: LinkBudget | None = None, # The transmission's link budget, if already computed
    ) -> TransmissionResult:

        if budget is None:
            budget = self.link_budget(transmission, link)
        if not budget.transmit:
            return self._outage(transmission, budget)
        sinr_db = self._sinr_db(budget, interference)
        extra = {'interference_power': interference} if interference else {}
        if sinr_db == -math.inf:                         # drowned (e.g. an interferer at the receiver's place)
            return self._lost(transmission, link, budget, sinr_db, **extra)
        message = transmission.message
        bits = np.asarray(self.codec.encode(message.payload))
        num_bits = int(bits.shape[-1])
        if budget.snr_db == math.inf:                    # same place: a perfect link
            return TransmissionResult(success=True, transmission=transmission, payload=message.payload,
                                      size_bits=int(bits.size), snr_db=math.inf, error_rate=0.0,
                                      metadata=self._metadata(budget, bit_errors=0))

        k = self.modulation.bits_per_symbol
        padded = np.pad(bits, [(0, 0)] * (bits.ndim - 1) + [(0, -num_bits % k)])
        symbols = self.modulation.modulate(padded)
        received = propagate(symbols, budget.h, budget.power, self.noise_power + interference, self.rng)  # interference as noise
        detected = np.asarray(self.modulation.demodulate(received, budget.h))[..., :num_bits]
        bit_errors = int((detected != bits).sum())
        success = not (self.drop_corrupted and bit_errors)
        latency, energy = self._timing(budget, int(np.size(symbols)), link)
        return TransmissionResult(
            success=success,
            transmission=transmission,
            payload=self.codec.decode(detected) if success else None,
            latency=latency,
            size_bits=int(bits.size),
            energy=energy,
            snr_db=sinr_db,
            error_rate=bit_errors / max(int(bits.size), 1),
            metadata=self._metadata(budget, bit_errors=bit_errors, **extra),
        )

    def _num_bits(self, message: Message) -> int:
        return int(np.size(self.codec.encode(message.payload)))

    def _num_symbols(self, num_bits: int) -> int:
        return -(-num_bits // self.modulation.bits_per_symbol)
