# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/metrics.ipynb.

# %% ../nbs/metrics.ipynb #b360c62e
from __future__ import annotations

from dataclasses import dataclass

from .core import Transmission, TransmissionResult




# %% auto #0
__all__ = ['CommunicationMetrics', 'MetricsCollector']

# %% ../nbs/metrics.ipynb #e9d675ac
@dataclass
class CommunicationMetrics:

    transmissions: int = 0
    successful: int = 0
    failed: int = 0

    bits_sent: int = 0
    bits_received: int = 0

    total_latency: float = 0.0
    total_energy: float = 0.0

    @property
    def packet_loss(self) -> float:
        if self.transmissions == 0:
            return 0.0

        return self.failed / self.transmissions

    @property
    def average_latency(self) -> float:
        if self.successful == 0:
            return 0.0

        return self.total_latency / self.successful



# %% ../nbs/metrics.ipynb #40d7df61
class MetricsCollector:

    def __init__(self):
        self.metrics = CommunicationMetrics()

    def record(
        self,
        transmission: Transmission,
        result: CommunicationMetrics | TransmissionResult,
    ):

        if not isinstance(result, TransmissionResult):
            return

        m = self.metrics

        m.transmissions += 1

        bits = result.size_bits

        m.bits_sent += bits

        if result.success:
            m.successful += 1
            m.bits_received += bits
            m.total_latency += result.latency

        else:
            m.failed += 1

        m.total_energy += result.energy

    def summary(self) -> CommunicationMetrics:
        return self.metrics
    
