"""What nodes send and receive through: it ties the topology, protocol, backend and metrics together.

Docs: https://Ahmed-Khaled-Saleh.github.io/comm-core/network.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/network.ipynb.

# %% ../nbs/network.ipynb #9741fe3d
from __future__ import annotations

from collections import defaultdict
from dataclasses import replace
from typing import Dict, List

from .backend import CommunicationBackend
from .core import Message, Node, TransmissionResult
from .metrics import MetricsCollector
from .protocol import Protocol
from .topology import Topology

# %% auto #0
__all__ = ['Network']

# %% ../nbs/network.ipynb #a2e742d8
class Network:

    def __init__(
        self,
        nodes: List[Node],
        topology: Topology,
        protocol: Protocol,
        backend: CommunicationBackend,
        metrics: MetricsCollector | None = None,
    ):
        self.nodes = {
            node.id: node
            for node in nodes
        }

        self.topology = topology
        self.protocol = protocol
        self.backend = backend

        self.metrics = (
            metrics
            if metrics is not None
            else MetricsCollector()
        )

        self._inbox: Dict[str, List[Message]] = (
            defaultdict(list)
        )

        self.time = 0.0

    def reset(self, seed: int | None = None) -> None:
        "Start over (e.g. a new episode): clock, queues, inboxes and metrics; `seed` reseeds the protocol and the backend."
        self.time = 0.0
        self._inbox.clear()
        self.protocol.reset(seed)
        self.backend.reset(seed)
        self.metrics.reset()

    def send(
        self,
        message: Message,
    ) -> None:

        if message.sender not in self.nodes:
            raise ValueError(
                f"Unknown sender: {message.sender}"
            )

        if message.receiver not in self.nodes:
            raise ValueError(
                f"Unknown receiver: {message.receiver}"
            )

        if not self.topology.is_connected(
            message.sender,
            message.receiver,
        ):
            raise ValueError(
                f"No link from "
                f"{message.sender} to "
                f"{message.receiver}"
            )

        self.protocol.submit(
            message,
            self.time,
        )

    def step(
        self,
        dt: float = 1.0,
    ) -> List[TransmissionResult]:

        self.time += dt

        self.backend.step(self.time)

        transmissions = self.protocol.schedule(
            self.time
        )

        # the step's transmissions happen at the same time: the backend gets them all at once
        links = [
            self.topology.get_link(
                transmission.sender,
                transmission.receiver,
            )
            for transmission in transmissions
        ]

        results = self.backend.transmit_all(
            list(zip(transmissions, links))
        )

        for transmission, result in zip(transmissions, results):

            self.metrics.record(
                transmission,
                result,
            )

            if result.success:

                # what the receiver gets is what the channel delivered (it may differ from what was sent)
                self._inbox[
                    transmission.receiver
                ].append(
                    replace(transmission.message, payload=result.payload)
                )

        # acknowledgements: the protocol learns what got through (e.g. to retransmit)
        self.protocol.feedback(results)

        return results

    def receive(
        self,
        node_id: str,
    ) -> List[Message]:

        messages = self._inbox[node_id]

        self._inbox[node_id] = []

        return messages

    
