"""Where a transmission's channel coefficient h comes from: fading models and ray-traced tables.

Docs: https://Ahmed-Khaled-Saleh.github.io/comm-core/propagation.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/propagation.ipynb.

# %% ../nbs/propagation.ipynb #b9d0d157
from __future__ import annotations

import math
import warnings
from abc import ABC, abstractmethod
from typing import Mapping, Sequence

import numpy as np

from .core import NodeId, Transmission
from .topology import Link

# %% auto #0
__all__ = ['Fading', 'NoFading', 'RayleighFading', 'RayTracedFading']

# %% ../nbs/propagation.ipynb #52ddf3cc
class Fading(ABC):
    "The channel coefficient h of a transmission."

    @abstractmethod
    def coefficient(
        self,
        transmission: Transmission, # The transmission (its sender and receiver)
        link: Link, # Its link
    ) -> complex:
        "h of this transmission (math.inf: the nodes are at the same place, which means a perfect link)."

    def reset(self, seed: int | None = None) -> None:
        "Start over; `seed` reseeds the fading's random generator, if it has one."
        pass


class NoFading(Fading):
    "The same coefficient for every transmission."

    def __init__(
        self,
        h: complex = 1.0, # The coefficient
    ):
        self.h = h

    def coefficient(self, transmission, link):
        return self.h


class RayleighFading(Fading):
    "h ~ CN(0, gain), drawn anew for every transmission (constant during a packet)."

    def __init__(
        self,
        gain: float = 1.0, # Average power gain E|h|^2 (the path loss)
        seed: int | None = None, # Seed of the draws
    ):
        self.gain = gain
        self.rng = np.random.default_rng(seed)

    def reset(self, seed=None):
        if seed is not None:
            self.rng = np.random.default_rng(seed)

    def coefficient(self, transmission, link):
        return complex(self.rng.standard_normal(), self.rng.standard_normal()) * math.sqrt(self.gain / 2)

# %% ../nbs/propagation.ipynb #6b413d3c
def _key(position) -> tuple:
    return tuple(np.asarray(position).reshape(-1).tolist())


class RayTracedFading(Fading):
    "Coefficients ray-traced beforehand (e.g. Sionna RT) between a set of positions, looked up where the nodes are."

    def __init__(
        self,
        H, # Channel coefficients `H[rx, tx]` between the positions: (N, N) or (N, N, num_subcarriers), complex
        positions: Sequence, # The N positions (e.g. grid cells (x, y)), in the order of H's indices
        node_positions: Mapping | None = None, # Where the nodes are to begin with (see `set_positions`)
    ):
        H = np.asarray(H)
        if H.ndim == 3:
            gain = (np.abs(H) ** 2).mean(axis=-1)
        elif H.ndim == 2:
            gain = np.abs(H) ** 2
        else:
            raise ValueError(f"H: (N, N) or (N, N, num_subcarriers), not {H.shape}")
        if gain.shape[0] != gain.shape[1] or gain.shape[0] != len(positions):
            raise ValueError(f"H is {H.shape[:2]} for {len(positions)} positions")
        self.gain = gain.astype(np.float64)
        self.H = (H if H.ndim == 2 else np.sqrt(self.gain)).astype(np.complex128)   # one coefficient per link
        self.positions = [_key(p) for p in positions]
        self.index = {p: i for i, p in enumerate(self.positions)}
        off = ~np.eye(len(self.positions), dtype=bool)
        if off.any() and np.allclose(self.gain[off], 1.0):
            warnings.warn("every link has |H|^2 = 1: the coefficients were normalized (paths.cfr(normalize=True)), "
                          "so the path loss is lost and every link is equally good; use normalize=False")
        self.node_positions: dict = {}
        self.set_positions(node_positions or {})

    @classmethod
    def from_files(
        cls,
        channel_path: str, # .npy of H[rx, tx]
        positions_path: str, # .npy of the positions
        **kwargs, # The other arguments of `RayTracedFading`
    ) -> RayTracedFading:
        "Load the arrays saved after ray tracing."
        return cls(np.load(channel_path), np.load(positions_path), **kwargs)

    def set_positions(
        self,
        positions: Mapping[NodeId, Sequence], # Position of (some of) the nodes, e.g. {'agent_0': (3, 5)}
    ) -> None:
        "Where the nodes are now."
        for node, p in positions.items():
            self.node_positions[node] = _key(p)

    def _index(self, node: NodeId) -> int:
        if node not in self.node_positions:
            raise KeyError(f"no position for node {node!r}: call set_positions first")
        p = self.node_positions[node]
        if p not in self.index:
            raise KeyError(f"node {node!r} is at {p}, where no channel was ray-traced ({len(self.index)} positions)")
        return self.index[p]

    def path_gain(self, sender: NodeId, receiver: NodeId) -> float:
        "Linear path gain |H|^2 from `sender` to `receiver` at their current positions (inf if co-located)."
        tx, rx = self._index(sender), self._index(receiver)
        return math.inf if tx == rx else float(self.gain[rx, tx])

    def coefficient(self, transmission, link):
        "H[rx, tx] at the nodes' current positions (math.inf if co-located)."
        tx, rx = self._index(transmission.sender), self._index(transmission.receiver)
        return math.inf if tx == rx else complex(self.H[rx, tx])
