# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/protocol.ipynb.

# %% ../nbs/protocol.ipynb #45b4c054
from __future__ import annotations

from abc import ABC, abstractmethod
from collections import deque
from typing import Deque, List

from .core import Message, Transmission



# %% auto #0
__all__ = ['Protocol', 'IdealProtocol']

# %% ../nbs/protocol.ipynb #009bee75
class Protocol(ABC):

    @abstractmethod
    def submit(
        self,
        message: Message,
        time: float,
    ) -> None:
        pass

    @abstractmethod
    def schedule(
        self,
        time: float,
    ) -> List[Transmission]:
        pass




# %% ../nbs/protocol.ipynb #a8a44d63
class IdealProtocol(Protocol):

    def __init__(self):
        self._queue: Deque[Message] = deque()

    def submit(
        self,
        message: Message,
        time: float,
    ) -> None:
        self._queue.append(message)

    def schedule(
        self,
        time: float,
    ) -> List[Transmission]:

        transmissions = []

        while self._queue:

            message = self._queue.popleft()

            transmissions.append(
                Transmission(
                    message=message,
                    sender=message.sender,
                    receiver=message.receiver,
                    start_time=time,
                    end_time=time,
                )
            )

        return transmissions
    
