"""When messages are transmitted: queues, time slots and medium access.

Docs: https://Ahmed-Khaled-Saleh.github.io/comm-core/protocol.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/protocol.ipynb.

# %% ../nbs/protocol.ipynb #1fafd5c1
from __future__ import annotations

from abc import ABC, abstractmethod
from collections import defaultdict, deque
from typing import Collection, Deque, Dict, List, Sequence

import numpy as np

from .core import Message, NodeId, Transmission, TransmissionResult



# %% auto #0
__all__ = ['Protocol', 'IdealProtocol', 'SlottedProtocol', 'TDMAProtocol', 'SlottedALOHA']

# %% ../nbs/protocol.ipynb #009bee75
class Protocol(ABC):

    @abstractmethod
    def submit(
        self,
        message: Message,
        time: float,
    ) -> None:
        pass

    def reset(self, seed: int | None = None) -> None:
        "Drop the queued messages (e.g. a new episode); `seed` reseeds the protocol's random generator, if it has one."
        pass

    def feedback(
        self,
        results: List[TransmissionResult], # The results of the transmissions just scheduled
    ) -> None:
        "What happened to the transmissions of the last step (an acknowledgement), e.g. to retransmit the lost ones."
        pass

    @abstractmethod
    def schedule(
        self,
        time: float,
    ) -> List[Transmission]:
        pass

# %% ../nbs/protocol.ipynb #a8a44d63
class IdealProtocol(Protocol):

    def __init__(self):
        self._queue: Deque[Message] = deque()

    def reset(self, seed: int | None = None) -> None:
        self._queue.clear()

    def submit(
        self,
        message: Message,
        time: float,
    ) -> None:
        self._queue.append(message)

    def schedule(
        self,
        time: float,
    ) -> List[Transmission]:

        transmissions = []

        while self._queue:

            message = self._queue.popleft()

            transmissions.append(
                Transmission(
                    message=message,
                    sender=message.sender,
                    receiver=message.receiver,
                    start_time=time,
                    end_time=time,
                )
            )

        return transmissions
    

# %% ../nbs/protocol.ipynb #46baabfd
class SlottedProtocol(Protocol):
    "Each network step is a slot; `senders` decides which nodes transmit in it, and the others' messages wait."

    def __init__(
        self,
        queue_size: int | None = None, # Messages waiting per sender; beyond it the oldest are dropped (None: no limit)
        max_retries: int = 0, # Retransmissions of a lost message (from the network's feedback)
    ):
        self.queue_size, self.max_retries = queue_size, max_retries
        self._queues: Dict[NodeId, Deque[Message]] = defaultdict(deque)
        self._attempts: Dict[str, int] = {}
        self.slot = 0
        self.dropped = 0                               # messages dropped because a queue was full

    @abstractmethod
    def senders(
        self,
        slot: int, # Index of the slot (0, 1, ...)
        waiting: List[NodeId], # The nodes with messages waiting
    ) -> Collection[NodeId]:
        "The nodes that transmit in this slot."

    def reset(self, seed: int | None = None) -> None:
        self._queues.clear()
        self._attempts.clear()
        self.slot = 0
        self.dropped = 0

    def submit(self, message: Message, time: float) -> None:
        queue = self._queues[message.sender]
        queue.append(message)
        if self.queue_size is not None and len(queue) > self.queue_size:
            dropped = queue.popleft()
            self._attempts.pop(dropped.id, None)
            self.dropped += 1

    def waiting(self, node: NodeId) -> int:
        "Number of messages `node` has waiting."
        return len(self._queues.get(node, ()))

    def schedule(self, time: float) -> List[Transmission]:
        waiting = [node for node, queue in self._queues.items() if queue]
        chosen = set(self.senders(self.slot, waiting))
        self.slot += 1
        transmissions = []
        for node in waiting:
            if node not in chosen:
                continue
            queue = self._queues[node]
            while queue:
                message = queue.popleft()
                transmissions.append(Transmission(message=message, sender=message.sender, receiver=message.receiver,
                                                  start_time=time, end_time=time))
        return transmissions

    def feedback(self, results: List[TransmissionResult]) -> None:
        "Lost messages go back to the front of their sender's queue, at most `max_retries` times."
        if not self.max_retries:
            return
        retry = []
        for result in results:
            message = result.transmission.message
            if result.success:
                self._attempts.pop(message.id, None)
                continue
            attempts = self._attempts.get(message.id, 0) + 1
            if attempts <= self.max_retries:
                self._attempts[message.id] = attempts
                retry.append(message)
            else:
                self._attempts.pop(message.id, None)
        for message in reversed(retry):
            self._queues[message.sender].appendleft(message)


class TDMAProtocol(SlottedProtocol):
    "Time division: each slot of a repeating frame belongs to some nodes, which alone transmit in it."

    def __init__(
        self,
        frame: Sequence, # Owners of each slot: node ids (one per slot), or collections of node ids sharing a slot
        queue_size: int | None = None, # Messages waiting per sender (see `SlottedProtocol`)
        max_retries: int = 0, # Retransmissions of a lost message
    ):
        super().__init__(queue_size, max_retries)
        self.frame = [{owner} if isinstance(owner, str) else set(owner) for owner in frame]
        if not self.frame:
            raise ValueError("the frame needs at least one slot")

    def senders(self, slot, waiting):
        return self.frame[slot % len(self.frame)]


class SlottedALOHA(SlottedProtocol):
    "Random access: in every slot, each node with waiting messages transmits with probability `p`."

    def __init__(
        self,
        p: float = 0.5, # Probability of transmitting in a slot
        queue_size: int | None = None, # Messages waiting per sender (see `SlottedProtocol`)
        max_retries: int = 0, # Retransmissions of a lost message
        seed: int | None = None, # Seed of the random access
    ):
        super().__init__(queue_size, max_retries)
        self.p = p
        self.rng = np.random.default_rng(seed)

    def reset(self, seed: int | None = None) -> None:
        super().reset(seed)
        if seed is not None:
            self.rng = np.random.default_rng([seed, 2])

    def senders(self, slot, waiting):
        return [node for node in waiting if self.rng.random() < self.p]
