"""A channel ray-traced beforehand with Sionna RT, loaded from numpy arrays.

Docs: https://Ahmed-Khaled-Saleh.github.io/comm-core/sionna_rt.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/sionna_rt.ipynb.

# %% ../nbs/sionna_rt.ipynb #f0cad1ea
from __future__ import annotations

import math
from typing import Mapping, Sequence

import numpy as np

from .core import NodeId
from .propagation import RayTracedFading
from .system import FixedPower, SystemLevelChannel, bpsk_bit_error_rate, packet_error_rate

# %% auto #0
__all__ = ['SionnaRTChannel']

# %% ../nbs/sionna_rt.ipynb #c47c3131
class SionnaRTChannel(SystemLevelChannel):
    "A channel ray-traced beforehand (Sionna RT) between a set of positions, at the system level."

    def __init__(
        self,
        H, # Channel coefficients `H[rx, tx]` between the positions: (N, N) or (N, N, num_subcarriers), complex
        positions: Sequence, # The N positions (e.g. grid cells (x, y)), in the order of H's indices
        noise_power_w: float = 1e-13, # Noise power at the receiver, W (1e-13 W = -100 dBm)
        per_model: str = 'bpsk', # Packet error rate of the SNR: 'bpsk' or 'threshold' (see `packet_error_rate`)
        snr_threshold_db: float = 10.0, # The 'threshold' model's SNR
        node_positions: Mapping | None = None, # Where the nodes are to begin with (see `set_positions`)
        seed: int | None = None, # Seed of the packet losses
        power_control=None, # Transmit power and outages; None: the link's tx_power_w
    ):
        super().__init__(RayTracedFading(H, positions, node_positions), power_control or FixedPower(),
                         noise_power_w, per_model, snr_threshold_db, seed)

    @classmethod
    def from_files(
        cls,
        channel_path: str, # .npy of H[rx, tx]
        positions_path: str, # .npy of the positions
        **kwargs, # The other arguments of `SionnaRTChannel`
    ) -> SionnaRTChannel:
        "Load the arrays saved after ray tracing."
        return cls(np.load(channel_path), np.load(positions_path), **kwargs)

    def path_gain(self, sender: NodeId, receiver: NodeId) -> float:
        "Linear path gain |H|^2 from `sender` to `receiver` at their current positions (inf if co-located)."
        return self.fading.path_gain(sender, receiver)

    def snr_db(self, sender: NodeId, receiver: NodeId, tx_power_w: float = 1.0) -> float:
        "SNR of a transmission from `sender` to `receiver` with `tx_power_w` (dB)."
        snr = tx_power_w * self.path_gain(sender, receiver) / self.noise_power
        return 10 * math.log10(snr) if snr > 0 else -math.inf
