"""5G NR packet error rates from Sionna SYS: LDPC tables, EESM over the subcarriers, link adaptation.

Docs: https://Ahmed-Khaled-Saleh.github.io/comm-core/sionna_sys.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/sionna_sys.ipynb.

# %% ../nbs/sionna_sys.ipynb #75ab5c60
from __future__ import annotations

import math
from typing import Sequence

import numpy as np

from .system import ErrorModel

# %% auto #0
__all__ = ['MAX_CODERATE', 'nr_allocation', 'SionnaErrorModel']

# %% ../nbs/sionna_sys.ipynb #3517e534
MAX_CODERATE = 0.95                                        # NR: a UE may skip decoding above this effective code rate


def nr_allocation(
    num_bits: int, # Payload size
    modulation_order: int, # Bits per QAM symbol of the MCS
    coderate: float, # Code rate of the MCS
) -> tuple:
    "(resource elements, TB size): the fewest resource elements whose NR transport block holds `num_bits`."
    import torch
    from sionna.phy.nr.utils import calculate_tb_size
    num_bits = max(int(num_bits), 1)
    first = max(1, math.ceil(num_bits / (modulation_order * coderate)))
    for lo in range(first, first + 100_000, 2048):         # candidates in chunks; usually the first ones fit
        re = torch.arange(lo, lo + 2048)
        tb, _, num_cb, tb_crc, cb_crc = calculate_tb_size(
            modulation_order=torch.full_like(re, modulation_order), target_coderate=torch.full(re.shape, float(coderate)),
            num_coded_bits=re * modulation_order, return_cw_length=False, verbose=False)
        rate = (tb + tb_crc + num_cb * cb_crc) / (re * modulation_order)
        fits = (tb >= num_bits) & (rate <= MAX_CODERATE)
        if fits.any():
            i = int(torch.nonzero(fits)[0])
            return int(re[i]), int(tb[i])
    raise ValueError(f"no NR allocation for {num_bits} bits")


class SionnaErrorModel(ErrorModel):
    "5G NR PHY abstraction of Sionna SYS: EESM over the subcarriers, LDPC BLER tables, an MCS per transmission."

    def __init__(
        self,
        mcs_index: int | None = None, # A fixed MCS; None: link adaptation, the highest MCS meeting `bler_target`
        bler_target: float = 0.1, # Link adaptation's target TBLER
        mcs_table_index: int = 1, # 5G NR MCS table: 1 (up to 64-QAM) or 2 (up to 256-QAM)
        mcs_category: int = 0, # 0: PUSCH (uplink), 1: PDSCH (downlink)
        device: str | None = None, # Torch device; None: Sionna's default (a GPU if there is one)
        precision: str = 'single', # 'single' or 'double'
        mcs_indices: Sequence[int] | None = None, # Link adaptation's candidate MCSs; None: all of the table's
    ):
        import torch
        from sionna.phy.nr.utils import MCSDecoderNR
        from sionna.sys import EESM, PHYAbstraction
        self._torch = torch
        self.phy = PHYAbstraction(precision=precision, device=device)
        self.eesm = EESM(precision=precision, device=device)
        self.device = self.phy.device
        self.dtype = torch.float64 if precision == 'double' else torch.float32
        self.bler_target, self.mcs_table_index, self.mcs_category = bler_target, mcs_table_index, mcs_category
        decoder = MCSDecoderNR(device=self.device)
        valid = []
        for m in range(32):                                # the MCS indices of this table
            try:
                decoder(torch.tensor([m], dtype=torch.int32, device=self.device), mcs_table_index=mcs_table_index,
                        mcs_category=mcs_category, check_validity=True)
                valid.append(m)
            except ValueError:
                pass
        if mcs_indices is not None:
            valid = [m for m in valid if m in set(mcs_indices)]
        if mcs_index is not None and mcs_index not in valid:
            raise ValueError(f"mcs_index {mcs_index}: one of {valid} for MCS table {mcs_table_index}")
        self.mcs_index = mcs_index
        self.mcs = torch.tensor(valid if mcs_index is None else [mcs_index], dtype=torch.int32, device=self.device)
        order, rate = decoder(self.mcs, mcs_table_index=mcs_table_index, mcs_category=mcs_category, check_validity=False)
        self.modulation_order, self.coderate = order.cpu().tolist(), rate.cpu().tolist()
        self._allocations = {}                             # (bits, MCS position) -> (resource elements, TB size)

    def allocation(
        self,
        num_bits: int, # Payload size
        mcs: int, # MCS index
    ) -> tuple:
        "(resource elements, TB size) of a payload at an MCS (see `nr_allocation`), cached."
        i = self.mcs.cpu().tolist().index(mcs)
        if (num_bits, i) not in self._allocations:
            self._allocations[num_bits, i] = nr_allocation(num_bits, self.modulation_order[i], self.coderate[i])
        return self._allocations[num_bits, i]

    def __call__(self, sinr, size_bits):
        torch = self._torch
        n, width, M = len(sinr), max(len(s) for s in sinr), len(self.mcs)
        grid = np.zeros((n, width))                        # 0: a subcarrier the transmission does not use
        for k, s in enumerate(sinr):
            grid[k, :len(s)] = np.minimum(s, 1e12)
        s = torch.as_tensor(grid, dtype=self.dtype, device=self.device)[:, None, :, None, None].expand(n, 1, width, M, 1)
        mcs = self.mcs[None].expand(n, M)
        sinr_eff = self.eesm(s, mcs, mcs_table_index=self.mcs_table_index, mcs_category=self.mcs_category)
        mcs_list = self.mcs.cpu().tolist()
        re = torch.as_tensor([[self.allocation(max(int(b), 1), m)[0] for m in mcs_list] for b in size_bits],
                             dtype=torch.int32, device=self.device)
        tbler = self.phy(mcs, sinr_eff=sinr_eff, num_allocated_re=re, mcs_table_index=self.mcs_table_index,
                         mcs_category=self.mcs_category, check_mcs_index_validity=False)[3]
        tbler = torch.nan_to_num(tbler, nan=1.0, posinf=1.0).clamp(0, 1)   # no table entry: lost
        if self.mcs_index is None:                          # the highest MCS meeting the target, else the lowest
            ok = tbler <= self.bler_target
            best = torch.where(ok.any(1), (ok * torch.arange(M, device=self.device)).argmax(1),
                               torch.zeros(n, dtype=torch.long, device=self.device))
        else:
            best = torch.zeros(n, dtype=torch.long, device=self.device)
        rows = torch.arange(n, device=self.device)
        per = tbler[rows, best].cpu().numpy().astype(float)
        res = re[rows, best].cpu().numpy().astype(int)
        eff = sinr_eff[rows, best].cpu().numpy().astype(float)
        mcs_used = self.mcs[best].cpu().numpy()
        info = [{'mcs': int(m), 'sinr_eff_db': 10 * math.log10(e) if e > 0 else -math.inf, 'resource_elements': int(r)}
                for m, e, r in zip(mcs_used, eff, res)]
        return per, res, info
