"""A channel ray-traced beforehand with Sionna RT, loaded from numpy arrays.

Docs: https://Ahmed-Khaled-Saleh.github.io/comm-core/sionna_rt.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/sionna_rt.ipynb.

# %% ../nbs/sionna_rt.ipynb #a6b1eb5e
from __future__ import annotations

import math
import random
import warnings
from typing import Mapping, Sequence

import numpy as np

from .channel import Channel
from .core import NodeId, Transmission, TransmissionResult
from .topology import Link

# %% auto #0
__all__ = ['bpsk_bit_error_rate', 'packet_error_rate', 'SionnaRTChannel']

# %% ../nbs/sionna_rt.ipynb #f446359f
def bpsk_bit_error_rate(
    snr: float, # Linear signal-to-noise ratio
) -> float:
    "Bit error rate of BPSK over AWGN: Q(sqrt(2 snr))."
    return 0.5 * math.erfc(math.sqrt(max(snr, 0.0)))


def packet_error_rate(
    snr_db: float, # Signal-to-noise ratio (dB); -inf: no signal
    size_bits: int, # Packet size
    model: str = 'bpsk', # 'bpsk' (independent BPSK bit errors) or 'threshold'
    threshold_db: float = 10.0, # 'threshold': packets at or above this SNR are received
) -> float:
    "Probability that a packet is lost."
    if snr_db == math.inf:
        return 0.0
    if snr_db == -math.inf:
        return 1.0
    if model == 'threshold':
        return 0.0 if snr_db >= threshold_db else 1.0
    if model == 'bpsk':
        ber = bpsk_bit_error_rate(10 ** (snr_db / 10))
        return 1.0 - (1.0 - ber) ** max(int(size_bits), 1)
    raise ValueError(f"model: 'bpsk' or 'threshold', not {model!r}")

# %% ../nbs/sionna_rt.ipynb #40a4d4ad
def _key(position) -> tuple:
    return tuple(np.asarray(position).reshape(-1).tolist())


class SionnaRTChannel(Channel):
    "A channel ray-traced beforehand (Sionna RT) between a set of positions; a link gets the channel of where its nodes are."

    def __init__(
        self,
        H, # Channel coefficients `H[rx, tx]` between the positions: (N, N) or (N, N, num_subcarriers), complex
        positions: Sequence, # The N positions (e.g. grid cells (x, y)), in the order of H's indices
        noise_power_w: float = 1e-13, # Noise power at the receiver, W (1e-13 W = -100 dBm)
        per_model: str = 'bpsk', # Packet error rate of the SNR: 'bpsk' or 'threshold' (see `packet_error_rate`)
        snr_threshold_db: float = 10.0, # The 'threshold' model's SNR
        node_positions: Mapping | None = None, # Where the nodes are to begin with (see `set_positions`)
        seed: int | None = None, # Seed of the packet losses
    ):
        H = np.asarray(H)
        if H.ndim == 3:
            gain = (np.abs(H) ** 2).mean(axis=-1)
        elif H.ndim == 2:
            gain = np.abs(H) ** 2
        else:
            raise ValueError(f"H: (N, N) or (N, N, num_subcarriers), not {H.shape}")
        if gain.shape[0] != gain.shape[1] or gain.shape[0] != len(positions):
            raise ValueError(f"H is {H.shape[:2]} for {len(positions)} positions")
        self.gain = gain.astype(np.float64)
        self.positions = [_key(p) for p in positions]
        self.index = {p: i for i, p in enumerate(self.positions)}
        off = ~np.eye(len(self.positions), dtype=bool)
        if off.any() and np.allclose(self.gain[off], 1.0):
            warnings.warn("every link has |H|^2 = 1: the coefficients were normalized (paths.cfr(normalize=True)), "
                          "so the path loss is lost and every link is equally good; use normalize=False")
        self.noise_power_w = noise_power_w
        self.per_model = per_model
        self.snr_threshold_db = snr_threshold_db
        self.node_positions: dict = {}
        self.set_positions(node_positions or {})
        self.rng = random.Random(seed)

    @classmethod
    def from_files(
        cls,
        channel_path: str, # .npy of H[rx, tx]
        positions_path: str, # .npy of the positions
        **kwargs, # The other arguments of `SionnaRTChannel`
    ) -> SionnaRTChannel:
        "Load the arrays saved after ray tracing."
        return cls(np.load(channel_path), np.load(positions_path), **kwargs)

    def set_positions(
        self,
        positions: Mapping[NodeId, Sequence], # Position of (some of) the nodes, e.g. {'agent_0': (3, 5)}
    ) -> None:
        "Where the nodes are now."
        for node, p in positions.items():
            self.node_positions[node] = _key(p)

    def reset(self, seed: int | None = None) -> None:
        "`seed` reseeds the packet losses."
        if seed is not None:
            self.rng.seed(seed)

    def _index(self, node: NodeId) -> int:
        if node not in self.node_positions:
            raise KeyError(f"no position for node {node!r}: call set_positions first")
        p = self.node_positions[node]
        if p not in self.index:
            raise KeyError(f"node {node!r} is at {p}, where no channel was ray-traced ({len(self.index)} positions)")
        return self.index[p]

    def path_gain(self, sender: NodeId, receiver: NodeId) -> float:
        "Linear path gain |H|^2 from `sender` to `receiver` at their current positions (inf if co-located)."
        tx, rx = self._index(sender), self._index(receiver)
        return math.inf if tx == rx else float(self.gain[rx, tx])

    def snr_db(self, sender: NodeId, receiver: NodeId, tx_power_w: float = 1.0) -> float:
        "SNR of a transmission from `sender` to `receiver` (dB)."
        snr = tx_power_w * self.path_gain(sender, receiver) / self.noise_power_w
        return 10 * math.log10(snr) if snr > 0 else -math.inf

    def transmit(
        self,
        transmission: Transmission,
        link: Link,
    ) -> TransmissionResult:

        message = transmission.message
        gain = self.path_gain(transmission.sender, transmission.receiver)
        snr_db = self.snr_db(transmission.sender, transmission.receiver, link.tx_power_w)
        per = packet_error_rate(snr_db, message.size_bits or 1, self.per_model, self.snr_threshold_db)
        success = self.rng.random() >= per

        return TransmissionResult(
            success=success,
            transmission=transmission,
            payload=message.payload if success else None,
            latency=0.0,
            size_bits=message.size_bits or 0,
            snr_db=snr_db,
            error_rate=per,
            metadata={'path_gain_db': 10 * math.log10(gain) if gain > 0 else -math.inf},
        )
