"""Many links, no bits: a PHY abstraction (SNR to packet error rate), power control, and the channel built on them.

Docs: https://Ahmed-Khaled-Saleh.github.io/comm-core/system.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/system.ipynb.

# %% ../nbs/system.ipynb #fbfb18fb
from __future__ import annotations

import math
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import List, Sequence, Tuple

import numpy as np

from .backend import CommunicationBackend
from .channel import Channel
from .core import Message, Transmission, TransmissionResult
from .propagation import Fading, NoFading
from .topology import Link

# %% auto #0
__all__ = ['bpsk_bit_error_rate', 'packet_error_rate', 'ErrorModel', 'BPSKErrorModel', 'ThresholdErrorModel', 'eesm',
           'EESMErrorModel', 'PowerControl', 'FixedPower', 'ChannelInversion', 'MessagePower', 'LinkBudget',
           'RadioChannel', 'SystemLevelChannel', 'InterferenceBackend']

# %% ../nbs/system.ipynb #bcdaea40
def _is_torch(x) -> bool:
    return type(x).__module__.partition('.')[0] == 'torch'


def _full(like, value, boolean: bool = False):
    "An array (or tensor) shaped like `like`, filled with `value`."
    if _is_torch(like):
        import torch
        return torch.full_like(like, value, dtype=torch.bool if boolean else None)
    return np.full(np.shape(like), value, dtype=bool if boolean else float)

# %% ../nbs/system.ipynb #08c10dae
def bpsk_bit_error_rate(
    snr: float, # Linear signal-to-noise ratio
) -> float:
    "Bit error rate of BPSK over AWGN: Q(sqrt(2 snr))."
    return 0.5 * math.erfc(math.sqrt(max(snr, 0.0)))


def packet_error_rate(
    snr_db: float, # Signal-to-noise ratio (dB); -inf: no signal
    size_bits: int, # Packet size
    model: str = 'bpsk', # 'bpsk' (independent BPSK bit errors) or 'threshold'
    threshold_db: float = 10.0, # 'threshold': packets at or above this SNR are received
) -> float:
    "Probability that a packet is lost."
    if snr_db == math.inf:
        return 0.0
    if snr_db == -math.inf:
        return 1.0
    if model == 'threshold':
        return 0.0 if snr_db >= threshold_db else 1.0
    if model == 'bpsk':
        ber = bpsk_bit_error_rate(10 ** (snr_db / 10))
        return 1.0 - (1.0 - ber) ** max(int(size_bits), 1)
    raise ValueError(f"model: 'bpsk' or 'threshold', not {model!r}")

# %% ../nbs/system.ipynb #22b17d15
class ErrorModel(ABC):
    "A PHY abstraction: the packet error rate of transmissions, from their SINR."

    @abstractmethod
    def __call__(
        self,
        sinr: List[np.ndarray], # Linear SINR of each transmission, at each of its subcarriers (one value: flat)
        size_bits: np.ndarray, # Packet size of each transmission
    ) -> Tuple[np.ndarray, np.ndarray, List[dict]]:
        "(packet error rates, symbols on the air, extra metadata) of the transmissions."


def _mean_snr_db(sinr: np.ndarray) -> float:
    snr = float(np.mean(sinr))
    return 10 * math.log10(snr) if snr > 0 else -math.inf


class BPSKErrorModel(ErrorModel):
    "Uncoded BPSK over AWGN at the mean SINR (see `packet_error_rate`); one symbol per bit."

    def __call__(self, sinr, size_bits):
        per = [packet_error_rate(_mean_snr_db(s), max(int(b), 1)) for s, b in zip(sinr, size_bits)]
        return np.array(per, float), np.asarray(size_bits, int), [{} for _ in sinr]


class ThresholdErrorModel(ErrorModel):
    "Received at or above an SINR (the mean over the subcarriers), lost below; one symbol per bit."

    def __init__(
        self,
        threshold_db: float = 10.0, # The SINR at which packets are received
    ):
        self.threshold_db = threshold_db

    def __call__(self, sinr, size_bits):
        per = [packet_error_rate(_mean_snr_db(s), 1, 'threshold', self.threshold_db) for s in sinr]
        return np.array(per, float), np.asarray(size_bits, int), [{} for _ in sinr]

# %% ../nbs/system.ipynb #f61e1534
def eesm(
    sinr: np.ndarray, # Linear SINR at each subcarrier
    beta: float, # EESM parameter (of an MCS)
) -> float:
    "Effective SINR (linear) of SINRs at several subcarriers: -β ln(mean(exp(-SINR/β)))."
    x = -np.asarray(sinr, float) / beta
    m = x.max()
    return float(max(-beta * (m + math.log(np.mean(np.exp(x - m)))), 0.0))


class EESMErrorModel(ErrorModel):
    "EESM over the subcarriers, then a logistic packet error rate: a PHY abstraction calibrated by its parameters (e.g. a Wi-Fi MCS)."

    def __init__(
        self,
        beta: float, # EESM parameter of the MCS
        threshold_db: float, # Effective SINR at which a `reference_bytes` packet is lost 10% of the time
        slope: float = 1.5, # Steepness of the waterfall (1/dB)
        reference_bytes: int = 1000, # Packet size of `threshold_db`; other sizes scale as independent pieces
        bits_per_symbol: float = 1.0, # For the symbols on the air (the latency of `SystemLevelChannel`)
    ):
        self.beta, self.threshold_db, self.slope = beta, threshold_db, slope
        self.reference_bytes, self.bits_per_symbol = reference_bytes, bits_per_symbol

    def __call__(self, sinr, size_bits):
        per, info = [], []
        for s, bits in zip(sinr, size_bits):
            eff = eesm(s, self.beta)
            eff_db = 10 * math.log10(eff) if eff > 0 else -math.inf
            if eff_db == -math.inf:
                p = 1.0
            else:
                p_ref = 1 / (1 + math.exp(min(self.slope * (eff_db - self.threshold_db) + math.log(9.0), 700)))
                p = 1 - (1 - p_ref) ** (max(int(bits), 1) / 8 / self.reference_bytes)
            per.append(p)
            info.append({'sinr_eff_db': eff_db})
        symbols = np.ceil(np.asarray(size_bits, float) / self.bits_per_symbol).astype(int)
        return np.array(per, float), symbols, info

# %% ../nbs/system.ipynb #67949a4b
class PowerControl(ABC):
    "How much power a transmission uses, and whether it is sent at all."

    @abstractmethod
    def allocate(
        self,
        gain, # Channel power gain |h|^2 (a number, an array or a tensor)
        noise_power, # Noise power at the receiver
        link: Link | None = None, # The link (for one transmission)
        message: Message | None = None, # The message (for one transmission)
    ):
        "(power, transmit): the transmit power, and whether to transmit (False: outage), shaped like `gain`."


class FixedPower(PowerControl):
    "The same power always."

    def __init__(
        self,
        power: float | None = None, # Transmit power; None: the link's `tx_power_w` (1 without a link)
    ):
        self.power = power

    def allocate(self, gain, noise_power, link=None, message=None):
        p = self.power if self.power is not None else (link.tx_power_w if link is not None else 1.0)
        return _full(gain, p), _full(gain, True, boolean=True)


class ChannelInversion(PowerControl):
    "Just enough power to reach `target_snr_db`: P = snr noise_power / |h|^2; links needing more than `max_power` are not used."

    def __init__(
        self,
        target_snr_db: float = 10.0, # SNR at the receiver
        max_power: float = math.inf, # Power budget
    ):
        self.target_snr_db, self.max_power = target_snr_db, max_power

    def allocate(self, gain, noise_power, link=None, message=None):
        if not (_is_torch(gain) or isinstance(gain, np.ndarray)):
            gain = np.float64(gain)
        with np.errstate(divide='ignore'):                 # |h|^2 = 0: infinite power, an outage
            power = 10 ** (self.target_snr_db / 10) * noise_power / gain
        return power, power <= self.max_power


class MessagePower(PowerControl):
    "The power the sender chose (e.g. a learned power control), in `message.metadata[key]`; no power or 0: not sent."

    def __init__(
        self,
        key: str = 'tx_power', # Metadata key of the power
        max_power: float = math.inf, # Larger powers are clipped to it
    ):
        self.key, self.max_power = key, max_power

    def allocate(self, gain, noise_power, link=None, message=None):
        if message is None:
            raise ValueError("MessagePower reads the power from the message")
        p = min(float(message.metadata.get(self.key, 0.0)), self.max_power)
        return p, p > 0

# %% ../nbs/system.ipynb #3c4f4175
def _child_seed(seed: int | None, i: int) -> int | None:
    return None if seed is None else int(np.random.SeedSequence([seed, i]).generate_state(1)[0])


@dataclass
class LinkBudget:
    "A transmission's channel, transmit power and SNR."
    h: complex # Channel coefficient; with subcarriers, √(mean |h|²) (math.inf: the nodes are at the same place)
    power: float # Transmit power
    transmit: bool # False: an outage, nothing is sent
    snr_db: float # P |h|^2 / noise power, dB (with subcarriers: the mean SNR)
    response: np.ndarray | None = None # h at each subcarrier (None: flat)

    @property
    def gain_db(self) -> float:
        "|h|^2 in dB."
        gain = abs(self.h) ** 2
        return 10 * math.log10(gain) if gain > 0 else -math.inf


class RadioChannel(Channel):
    "A channel over radio links: h from a fading, P from a power control, noise; subclasses decide what arrives."

    def __init__(
        self,
        fading: Fading | None = None, # The coefficient h of a transmission; None: `NoFading()` (h = 1)
        power_control: PowerControl | None = None, # Transmit power and outages; None: `FixedPower()` (the link's tx_power_w)
        noise_power: float = 1.0, # Noise power at the receiver (same unit as the power)
        seed: int | None = None, # Seed of the channel's randomness and of the fading
    ):
        self.fading = fading if fading is not None else NoFading()
        self.power_control = power_control if power_control is not None else FixedPower()
        self.noise_power = noise_power
        self.rng = np.random.default_rng()
        self.reset(seed)

    def reset(self, seed: int | None = None) -> None:
        "`seed` reseeds the channel and the fading."
        if seed is not None:
            self.rng = np.random.default_rng(_child_seed(seed, 0))
        self.fading.reset(_child_seed(seed, 1))

    def set_positions(self, positions) -> None:
        "Where the nodes are, for a fading that depends on it (e.g. `RayTracedFading`)."
        if hasattr(self.fading, 'set_positions'):
            self.fading.set_positions(positions)

    def link_budget(
        self,
        transmission: Transmission,
        link: Link,
    ) -> LinkBudget:
        "The channel, power and SNR of a transmission (nodes at the same place: a perfect link)."
        response = np.asarray(self.fading.response(transmission, link), np.complex128).reshape(-1)
        if np.isinf(response).any():
            return LinkBudget(complex(math.inf), 0.0, link.enabled, math.inf)
        h = complex(response[0]) if response.size == 1 else complex(np.sqrt(np.mean(np.abs(response) ** 2)))
        gain = abs(h) ** 2
        power, transmit = self.power_control.allocate(gain, self.noise_power, link=link, message=transmission.message)
        power = float(power)
        snr = power * gain / self.noise_power
        return LinkBudget(h, power, bool(transmit) and link.enabled, 10 * math.log10(snr) if snr > 0 else -math.inf,
                          response if response.size > 1 else None)

    def _sinr(self, budget: LinkBudget, interference: float = 0.0) -> np.ndarray:
        "Linear SINR at each subcarrier: P |h_k|^2 / (noise power + interference)."
        gains = np.abs(budget.response) ** 2 if budget.response is not None else np.array([abs(budget.h) ** 2])
        return budget.power * gains / (self.noise_power + interference)

    def _sinr_db(self, budget: LinkBudget, interference: float = 0.0) -> float:
        "P |h|^2 / (noise power + interference), dB: the SNR without interference."
        if budget.snr_db == math.inf or not interference:
            return budget.snr_db
        sinr = budget.power * abs(budget.h) ** 2 / (self.noise_power + interference)
        return 10 * math.log10(sinr) if sinr > 0 else -math.inf

    def _num_bits(self, message: Message) -> int:
        "Bits of a message on the air."
        return message.size_bits or 0

    def _num_symbols(self, num_bits: int) -> int:
        return num_bits

    def _lost(self, transmission: Transmission, link: Link, budget: LinkBudget, snr_db: float, **reason) -> TransmissionResult:
        "Sent (and paid for), but not received."
        bits = self._num_bits(transmission.message)
        latency, energy = self._timing(budget, self._num_symbols(bits), link)
        return TransmissionResult(success=False, transmission=transmission, payload=None, latency=latency, size_bits=bits,
                                  energy=energy, snr_db=snr_db, error_rate=1.0, metadata=self._metadata(budget, **reason))

    def _metadata(self, budget: LinkBudget, **extra) -> dict:
        return {'channel_gain_db': budget.gain_db, 'tx_power': budget.power if budget.transmit else 0.0, **extra}

    def _outage(self, transmission: Transmission, budget: LinkBudget) -> TransmissionResult:
        return TransmissionResult(success=False, transmission=transmission, payload=None, size_bits=0,
                                  snr_db=budget.snr_db, metadata=self._metadata(budget, outage=True))

    @staticmethod
    def _timing(budget: LinkBudget, num_symbols: int, link: Link) -> tuple:
        "(latency, energy) of `num_symbols` symbols."
        duration = num_symbols / link.bandwidth_hz if math.isfinite(link.bandwidth_hz) else 0.0
        return duration, budget.power * (duration if duration else num_symbols)

# %% ../nbs/system.ipynb #d8c711e9
class SystemLevelChannel(RadioChannel):
    "A PHY abstraction: SINR -> packet error rate -> the packet arrives intact or is lost. No bits are simulated."

    def __init__(
        self,
        fading: Fading | None = None, # The coefficient h of a transmission; None: h = 1
        power_control: PowerControl | None = None, # Transmit power and outages; None: the link's tx_power_w
        noise_power: float = 1.0, # Noise power at the receiver
        per_model: str | ErrorModel = 'bpsk', # 'bpsk', 'threshold', or an `ErrorModel` (e.g. `SionnaErrorModel`)
        snr_threshold_db: float = 10.0, # The 'threshold' model's SNR
        seed: int | None = None, # Seed of the packet losses and the fading
    ):
        if isinstance(per_model, ErrorModel):
            self.error_model = per_model
        elif per_model == 'bpsk':
            self.error_model = BPSKErrorModel()
        elif per_model == 'threshold':
            self.error_model = ThresholdErrorModel(snr_threshold_db)
        else:
            raise ValueError(f"per_model: 'bpsk', 'threshold' or an ErrorModel, not {per_model!r}")
        self.per_model, self.snr_threshold_db = per_model, snr_threshold_db
        super().__init__(fading, power_control, noise_power, seed)

    def transmit(
        self,
        transmission: Transmission,
        link: Link,
        interference: float = 0.0, # Power of the other transmissions at the receiver (see `InterferenceBackend`)
        budget: LinkBudget | None = None, # The transmission's link budget, if already computed
    ) -> TransmissionResult:
        return self.transmit_batch([(transmission, link)], [interference], [budget])[0]

    def transmit_batch(
        self,
        transmissions: List[Tuple[Transmission, Link]], # Transmissions, with their links
        interference: Sequence[float] | None = None, # Power of the other transmissions at each receiver
        budgets: Sequence[LinkBudget | None] | None = None, # Their link budgets, if already computed
    ) -> List[TransmissionResult]:
        "Several transmissions, with one call of the error model (much faster with `SionnaErrorModel`)."
        n = len(transmissions)
        interference = list(interference) if interference is not None else [0.0] * n
        budgets = [b if b is not None else self.link_budget(t, link)
                   for (t, link), b in zip(transmissions, budgets if budgets is not None else [None] * n)]
        sent = [k for k in range(n) if budgets[k].transmit]
        rated = [k for k in sent if budgets[k].snr_db != math.inf]     # nodes at the same place: a perfect link
        per = {k: 0.0 for k in sent}
        symbols = {k: transmissions[k][0].message.size_bits or 0 for k in sent}
        extra = {k: {} for k in sent}
        if rated:
            p, s, info = self.error_model([self._sinr(budgets[k], interference[k]) for k in rated],
                                          np.array([transmissions[k][0].message.size_bits or 1 for k in rated]))
            for k, pk, sk, ik in zip(rated, p, s, info):
                per[k], symbols[k], extra[k] = float(pk), int(sk), ik
        results = [None] * n
        for k in range(n):
            (t, link), budget = transmissions[k], budgets[k]
            if not budget.transmit:
                results[k] = self._outage(t, budget)
                continue
            success = bool(self.rng.random() >= per[k])
            latency, energy = self._timing(budget, symbols[k], link)
            metadata = {**({'interference_power': interference[k]} if interference[k] else {}), **extra[k]}
            results[k] = TransmissionResult(
                success=success,
                transmission=t,
                payload=t.message.payload if success else None,
                latency=latency,
                size_bits=t.message.size_bits or 0,
                energy=energy,
                snr_db=self._sinr_db(budget, interference[k]),
                error_rate=per[k],
                metadata=self._metadata(budget, **metadata),
            )
        return results

# %% ../nbs/system.ipynb #8cca0276
class InterferenceBackend(CommunicationBackend):
    "The transmissions of a step share the medium: each one's SINR counts the power of the other senders at its receiver."

    def __init__(
        self,
        channel: RadioChannel, # System or link level; its fading also gives the interfering paths
        half_duplex: bool = True, # A node that transmits in a step cannot receive in it
    ):
        self.channel, self.half_duplex = channel, half_duplex

    def transmit(self, transmission: Transmission, link: Link) -> TransmissionResult:
        "A transmission alone: no interference."
        return self.channel.transmit(transmission, link)

    def transmit_all(
        self,
        transmissions: List[Tuple[Transmission, Link]], # The transmissions of one step, with their links
    ) -> List[TransmissionResult]:
        "The transmissions of one step, at the same time."
        budgets = [self.channel.link_budget(t, link) for t, link in transmissions]
        emitted = {}                                   # sender -> its power on the air (its strongest transmission)
        for (t, _), budget in zip(transmissions, budgets):
            if budget.transmit:
                emitted[t.sender] = max(emitted.get(t.sender, 0.0), budget.power)
        gains = {}                                     # |h|^2 of the interfering paths, once per step

        def gain(sender, receiver, message):
            if (sender, receiver) not in gains:
                path = Transmission(message=message, sender=sender, receiver=receiver, start_time=0.0)
                gains[sender, receiver] = abs(complex(self.channel.fading.coefficient(path, Link(sender, receiver)))) ** 2
            return gains[sender, receiver]

        results = [None] * len(transmissions)
        heard, interference = [], []
        for k, ((t, link), budget) in enumerate(zip(transmissions, budgets)):
            if budget.transmit and self.half_duplex and t.receiver in emitted:
                results[k] = self.channel._lost(t, link, budget, budget.snr_db, half_duplex=True)
                continue
            heard.append(k)
            interference.append(sum(p * gain(s, t.receiver, t.message) for s, p in emitted.items()
                                    if p > 0 and s not in (t.sender, t.receiver)))
        if hasattr(self.channel, 'transmit_batch'):                 # one call of the error model for the step
            out = self.channel.transmit_batch([transmissions[k] for k in heard], interference, [budgets[k] for k in heard])
        else:
            out = [self.channel.transmit(*transmissions[k], interference=i, budget=budgets[k]) for k, i in zip(heard, interference)]
        for k, result in zip(heard, out):
            results[k] = result
        return results

    def reset(self, seed: int | None = None) -> None:
        self.channel.reset(seed)

    def step(self, time: float) -> None:
        self.channel.update(time)
