"""Many links, no bits: a PHY abstraction (SNR to packet error rate), power control, and the channel built on them.

Docs: https://Ahmed-Khaled-Saleh.github.io/comm-core/system.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/system.ipynb.

# %% ../nbs/system.ipynb #fbfb18fb
from __future__ import annotations

import math
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import List, Tuple

import numpy as np

from .backend import CommunicationBackend
from .channel import Channel
from .core import Message, Transmission, TransmissionResult
from .propagation import Fading, NoFading
from .topology import Link

# %% auto #0
__all__ = ['bpsk_bit_error_rate', 'packet_error_rate', 'PowerControl', 'FixedPower', 'ChannelInversion', 'MessagePower',
           'LinkBudget', 'RadioChannel', 'SystemLevelChannel', 'InterferenceBackend']

# %% ../nbs/system.ipynb #bcdaea40
def _is_torch(x) -> bool:
    return type(x).__module__.partition('.')[0] == 'torch'


def _full(like, value, boolean: bool = False):
    "An array (or tensor) shaped like `like`, filled with `value`."
    if _is_torch(like):
        import torch
        return torch.full_like(like, value, dtype=torch.bool if boolean else None)
    return np.full(np.shape(like), value, dtype=bool if boolean else float)

# %% ../nbs/system.ipynb #08c10dae
def bpsk_bit_error_rate(
    snr: float, # Linear signal-to-noise ratio
) -> float:
    "Bit error rate of BPSK over AWGN: Q(sqrt(2 snr))."
    return 0.5 * math.erfc(math.sqrt(max(snr, 0.0)))


def packet_error_rate(
    snr_db: float, # Signal-to-noise ratio (dB); -inf: no signal
    size_bits: int, # Packet size
    model: str = 'bpsk', # 'bpsk' (independent BPSK bit errors) or 'threshold'
    threshold_db: float = 10.0, # 'threshold': packets at or above this SNR are received
) -> float:
    "Probability that a packet is lost."
    if snr_db == math.inf:
        return 0.0
    if snr_db == -math.inf:
        return 1.0
    if model == 'threshold':
        return 0.0 if snr_db >= threshold_db else 1.0
    if model == 'bpsk':
        ber = bpsk_bit_error_rate(10 ** (snr_db / 10))
        return 1.0 - (1.0 - ber) ** max(int(size_bits), 1)
    raise ValueError(f"model: 'bpsk' or 'threshold', not {model!r}")

# %% ../nbs/system.ipynb #67949a4b
class PowerControl(ABC):
    "How much power a transmission uses, and whether it is sent at all."

    @abstractmethod
    def allocate(
        self,
        gain, # Channel power gain |h|^2 (a number, an array or a tensor)
        noise_power, # Noise power at the receiver
        link: Link | None = None, # The link (for one transmission)
        message: Message | None = None, # The message (for one transmission)
    ):
        "(power, transmit): the transmit power, and whether to transmit (False: outage), shaped like `gain`."


class FixedPower(PowerControl):
    "The same power always."

    def __init__(
        self,
        power: float | None = None, # Transmit power; None: the link's `tx_power_w` (1 without a link)
    ):
        self.power = power

    def allocate(self, gain, noise_power, link=None, message=None):
        p = self.power if self.power is not None else (link.tx_power_w if link is not None else 1.0)
        return _full(gain, p), _full(gain, True, boolean=True)


class ChannelInversion(PowerControl):
    "Just enough power to reach `target_snr_db`: P = snr noise_power / |h|^2; links needing more than `max_power` are not used."

    def __init__(
        self,
        target_snr_db: float = 10.0, # SNR at the receiver
        max_power: float = math.inf, # Power budget
    ):
        self.target_snr_db, self.max_power = target_snr_db, max_power

    def allocate(self, gain, noise_power, link=None, message=None):
        if not (_is_torch(gain) or isinstance(gain, np.ndarray)):
            gain = np.float64(gain)
        with np.errstate(divide='ignore'):                 # |h|^2 = 0: infinite power, an outage
            power = 10 ** (self.target_snr_db / 10) * noise_power / gain
        return power, power <= self.max_power


class MessagePower(PowerControl):
    "The power the sender chose (e.g. a learned power control), in `message.metadata[key]`; no power or 0: not sent."

    def __init__(
        self,
        key: str = 'tx_power', # Metadata key of the power
        max_power: float = math.inf, # Larger powers are clipped to it
    ):
        self.key, self.max_power = key, max_power

    def allocate(self, gain, noise_power, link=None, message=None):
        if message is None:
            raise ValueError("MessagePower reads the power from the message")
        p = min(float(message.metadata.get(self.key, 0.0)), self.max_power)
        return p, p > 0

# %% ../nbs/system.ipynb #3c4f4175
def _child_seed(seed: int | None, i: int) -> int | None:
    return None if seed is None else int(np.random.SeedSequence([seed, i]).generate_state(1)[0])


@dataclass
class LinkBudget:
    "A transmission's channel coefficient, transmit power and SNR."
    h: complex # Channel coefficient (math.inf: the nodes are at the same place)
    power: float # Transmit power
    transmit: bool # False: an outage, nothing is sent
    snr_db: float # P |h|^2 / noise power, dB

    @property
    def gain_db(self) -> float:
        "|h|^2 in dB."
        gain = abs(self.h) ** 2
        return 10 * math.log10(gain) if gain > 0 else -math.inf


class RadioChannel(Channel):
    "A channel over radio links: h from a fading, P from a power control, noise; subclasses decide what arrives."

    def __init__(
        self,
        fading: Fading | None = None, # The coefficient h of a transmission; None: `NoFading()` (h = 1)
        power_control: PowerControl | None = None, # Transmit power and outages; None: `FixedPower()` (the link's tx_power_w)
        noise_power: float = 1.0, # Noise power at the receiver (same unit as the power)
        seed: int | None = None, # Seed of the channel's randomness and of the fading
    ):
        self.fading = fading if fading is not None else NoFading()
        self.power_control = power_control if power_control is not None else FixedPower()
        self.noise_power = noise_power
        self.rng = np.random.default_rng()
        self.reset(seed)

    def reset(self, seed: int | None = None) -> None:
        "`seed` reseeds the channel and the fading."
        if seed is not None:
            self.rng = np.random.default_rng(_child_seed(seed, 0))
        self.fading.reset(_child_seed(seed, 1))

    def set_positions(self, positions) -> None:
        "Where the nodes are, for a fading that depends on it (e.g. `RayTracedFading`)."
        if hasattr(self.fading, 'set_positions'):
            self.fading.set_positions(positions)

    def link_budget(
        self,
        transmission: Transmission,
        link: Link,
    ) -> LinkBudget:
        "The coefficient, power and SNR of a transmission (nodes at the same place: a perfect link)."
        h = complex(self.fading.coefficient(transmission, link))
        gain = abs(h) ** 2
        if math.isinf(gain):
            return LinkBudget(h, 0.0, link.enabled, math.inf)
        power, transmit = self.power_control.allocate(gain, self.noise_power, link=link, message=transmission.message)
        power = float(power)
        snr = power * gain / self.noise_power
        return LinkBudget(h, power, bool(transmit) and link.enabled, 10 * math.log10(snr) if snr > 0 else -math.inf)

    def _sinr_db(self, budget: LinkBudget, interference: float = 0.0) -> float:
        "P |h|^2 / (noise power + interference), dB: the SNR without interference."
        if budget.snr_db == math.inf or not interference:
            return budget.snr_db
        sinr = budget.power * abs(budget.h) ** 2 / (self.noise_power + interference)
        return 10 * math.log10(sinr) if sinr > 0 else -math.inf

    def _num_bits(self, message: Message) -> int:
        "Bits of a message on the air."
        return message.size_bits or 0

    def _num_symbols(self, num_bits: int) -> int:
        return num_bits

    def _lost(self, transmission: Transmission, link: Link, budget: LinkBudget, snr_db: float, **reason) -> TransmissionResult:
        "Sent (and paid for), but not received."
        bits = self._num_bits(transmission.message)
        latency, energy = self._timing(budget, self._num_symbols(bits), link)
        return TransmissionResult(success=False, transmission=transmission, payload=None, latency=latency, size_bits=bits,
                                  energy=energy, snr_db=snr_db, error_rate=1.0, metadata=self._metadata(budget, **reason))

    def _metadata(self, budget: LinkBudget, **extra) -> dict:
        return {'channel_gain_db': budget.gain_db, 'tx_power': budget.power if budget.transmit else 0.0, **extra}

    def _outage(self, transmission: Transmission, budget: LinkBudget) -> TransmissionResult:
        return TransmissionResult(success=False, transmission=transmission, payload=None, size_bits=0,
                                  snr_db=budget.snr_db, metadata=self._metadata(budget, outage=True))

    @staticmethod
    def _timing(budget: LinkBudget, num_symbols: int, link: Link) -> tuple:
        "(latency, energy) of `num_symbols` symbols."
        duration = num_symbols / link.bandwidth_hz if math.isfinite(link.bandwidth_hz) else 0.0
        return duration, budget.power * (duration if duration else num_symbols)

# %% ../nbs/system.ipynb #d8c711e9
class SystemLevelChannel(RadioChannel):
    "A PHY abstraction: SNR -> packet error rate -> the packet arrives intact or is lost. No bits are simulated."

    def __init__(
        self,
        fading: Fading | None = None, # The coefficient h of a transmission; None: h = 1
        power_control: PowerControl | None = None, # Transmit power and outages; None: the link's tx_power_w
        noise_power: float = 1.0, # Noise power at the receiver
        per_model: str = 'bpsk', # Packet error rate of the SNR: 'bpsk' or 'threshold' (see `packet_error_rate`)
        snr_threshold_db: float = 10.0, # The 'threshold' model's SNR
        seed: int | None = None, # Seed of the packet losses and the fading
    ):
        self.per_model, self.snr_threshold_db = per_model, snr_threshold_db
        super().__init__(fading, power_control, noise_power, seed)

    def transmit(
        self,
        transmission: Transmission,
        link: Link,
        interference: float = 0.0, # Power of the other transmissions at the receiver (see `InterferenceBackend`)
        budget: LinkBudget | None = None, # The transmission's link budget, if already computed
    ) -> TransmissionResult:

        if budget is None:
            budget = self.link_budget(transmission, link)
        if not budget.transmit:
            return self._outage(transmission, budget)
        sinr_db = self._sinr_db(budget, interference)
        message = transmission.message
        size_bits = message.size_bits or 0
        per = packet_error_rate(sinr_db, size_bits or 1, self.per_model, self.snr_threshold_db)
        success = bool(self.rng.random() >= per)
        latency, energy = self._timing(budget, size_bits, link)
        return TransmissionResult(
            success=success,
            transmission=transmission,
            payload=message.payload if success else None,
            latency=latency,
            size_bits=size_bits,
            energy=energy,
            snr_db=sinr_db,
            error_rate=per,
            metadata=self._metadata(budget, **({'interference_power': interference} if interference else {})),
        )

# %% ../nbs/system.ipynb #8cca0276
class InterferenceBackend(CommunicationBackend):
    "The transmissions of a step share the medium: each one's SINR counts the power of the other senders at its receiver."

    def __init__(
        self,
        channel: RadioChannel, # System or link level; its fading also gives the interfering paths
        half_duplex: bool = True, # A node that transmits in a step cannot receive in it
    ):
        self.channel, self.half_duplex = channel, half_duplex

    def transmit(self, transmission: Transmission, link: Link) -> TransmissionResult:
        "A transmission alone: no interference."
        return self.channel.transmit(transmission, link)

    def transmit_all(
        self,
        transmissions: List[Tuple[Transmission, Link]], # The transmissions of one step, with their links
    ) -> List[TransmissionResult]:
        "The transmissions of one step, at the same time."
        budgets = [self.channel.link_budget(t, link) for t, link in transmissions]
        emitted = {}                                   # sender -> its power on the air (its strongest transmission)
        for (t, _), budget in zip(transmissions, budgets):
            if budget.transmit:
                emitted[t.sender] = max(emitted.get(t.sender, 0.0), budget.power)
        gains = {}                                     # |h|^2 of the interfering paths, once per step

        def gain(sender, receiver, message):
            if (sender, receiver) not in gains:
                path = Transmission(message=message, sender=sender, receiver=receiver, start_time=0.0)
                gains[sender, receiver] = abs(complex(self.channel.fading.coefficient(path, Link(sender, receiver)))) ** 2
            return gains[sender, receiver]

        results = []
        for (t, link), budget in zip(transmissions, budgets):
            if budget.transmit and self.half_duplex and t.receiver in emitted:
                results.append(self.channel._lost(t, link, budget, budget.snr_db, half_duplex=True))
                continue
            interference = sum(p * gain(s, t.receiver, t.message) for s, p in emitted.items()
                               if p > 0 and s not in (t.sender, t.receiver))
            results.append(self.channel.transmit(t, link, interference=interference, budget=budget))
        return results

    def reset(self, seed: int | None = None) -> None:
        self.channel.reset(seed)

    def step(self, time: float) -> None:
        self.channel.update(time)
